spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  profiles:
    active: prod
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  security:
    oauth2.client:
      registration:
        kakao:
          client-id: ${KAKAO_RESTAPI_KEY}
          redirect-uri: ${KAKAO_REDIRECT_URI}
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          client-name: Kakao
          scope:
            - profile_nickname
            - account_email
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  springfox:
    documentation:
      swagger:
        use-model-v3: false

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
